# Generated by Django 5.2.8 on 2025-11-24 16:29

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TradeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_name', models.CharField(max_length=100, verbose_name='Игрок')),
                ('items', models.JSONField(default=list, verbose_name='Вещи')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Время')),
            ],
            options={
                'verbose_name': 'Лог Трейда',
                'verbose_name_plural': 'Логи Трейдов',
                'ordering': ['-created_at'],
            },
        ),
    ]
