# Generated by Django 5.2.8 on 2025-11-24 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradelog',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveField(
            model_name='tradelog',
            name='player_name',
        ),
        migrations.AddField(
            model_name='tradelog',
            name='bot_name',
            field=models.CharField(default='Bot', max_length=100, verbose_name='Бот (Приемщик)'),
        ),
        migrations.AddField(
            model_name='tradelog',
            name='sender_name',
            field=models.CharField(default='Unknown', max_length=100, verbose_name='Отправитель'),
        ),
    ]
