# Generated by Django 5.2.8 on 2025-11-24 20:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0002_alter_tradelog_options_remove_tradelog_player_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CoinflipGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player1', models.CharField(max_length=100)),
                ('items1', models.JSONField(default=list)),
                ('player2', models.CharField(blank=True, max_length=100, null=True)),
                ('items2', models.JSONField(default=list)),
                ('winner', models.CharField(blank=True, max_length=100, null=True)),
                ('random_result', models.IntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100, verbose_name='Владелец')),
                ('item_name', models.CharField(max_length=100, verbose_name='Название предмета')),
                ('status', models.CharField(default='available', max_length=20)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
