# Generated by Django 5.2.8 on 2025-11-24 21:58

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0003_coinflipgame_useritem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tradelog',
            options={},
        ),
        migrations.AddField(
            model_name='coinflipgame',
            name='value1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='coinflipgame',
            name='value2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='useritem',
            name='item_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='bot_name',
            field=models.CharField(default='Bot', max_length=100),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='items',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='tradelog',
            name='sender_name',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='item_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='owner_name',
            field=models.CharField(max_length=100),
        ),
    ]
