# Generated by Django 5.2.8 on 2025-11-25 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0004_alter_tradelog_options_coinflipgame_value1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinflipgame',
            name='creator_side',
            field=models.CharField(default='green', max_length=10),
        ),
    ]
