# Generated by Django 5.2.8 on 2025-11-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0006_withdrawrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='amount',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='withdrawrequest',
            name='amount',
            field=models.IntegerField(default=1),
        ),
    ]
