# Generated by Django 5.2.8 on 2025-11-29 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0007_useritem_amount_withdrawrequest_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
