# Generated by Django 5.2.8 on 2025-12-05 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0008_useritem_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinflipgame',
            name='p1_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinflipgame',
            name='p2_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
