# Generated by Django 5.2.8 on 2025-12-05 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0009_coinflipgame_p1_viewed_coinflipgame_p2_viewed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinflipgame',
            name='p1_viewed',
        ),
        migrations.RemoveField(
            model_name='coinflipgame',
            name='p2_viewed',
        ),
    ]
