# Generated by Django 5.2.8 on 2025-12-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0010_remove_coinflipgame_p1_viewed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinflipgame',
            name='player1_viewed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='coinflipgame',
            name='player2_viewed',
            field=models.BooleanField(default=False),
        ),
    ]
