# Generated by Django 5.2.8 on 2026-03-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0013_giveaway'),
    ]

    operations = [
        migrations.AddField(
            model_name='coinflipgame',
            name='game_hash',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
    ]
