# Generated by Django 5.2.12 on 2026-04-07 06:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('casino', '0015_userchatprefix'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommissionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winner', models.CharField(max_length=100)),
                ('item_name', models.CharField(max_length=100)),
                ('item_value', models.IntegerField(default=0)),
                ('item_id', models.IntegerField()),
                ('total_pot', models.IntegerField(default=0)),
                ('total_items', models.IntegerField(default=0)),
                ('target_commission', models.FloatField(default=0)),
                ('actual_percent', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commissions', to='casino.coinflipgame')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
