"""
Django settings for mmflip project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from dotenv import load_dotenv
from urllib.parse import quote_plus

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Загружаем переменные из .env (для локальной разработки)
load_dotenv(BASE_DIR / '.env')


def _get_postgres_url():
    """Собирает URL для PostgreSQL из переменных окружения."""
    database_url = (
        os.environ.get('DATABASE_PUBLIC_URL', '').strip()
        or os.environ.get('DATABASE_URL', '').strip()
    )

    if not database_url:
        pg_database = os.environ.get('PGDATABASE', '').strip()
        pg_user = os.environ.get('PGUSER', '').strip()
        pg_password = os.environ.get('PGPASSWORD', '').strip()
        pg_host = os.environ.get('PGHOST', '').strip()
        pg_port = os.environ.get('PGPORT', '5432').strip()

        if all([pg_database, pg_user, pg_password, pg_host]):
            database_url = (
                f"postgresql://{quote_plus(pg_user)}:{quote_plus(pg_password)}"
                f"@{pg_host}:{pg_port}/{quote_plus(pg_database)}"
            )

    return database_url


def _get_sqlite_config():
    """Конфиг для локальной SQLite."""
    return dj_database_url.parse(
        f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=600,
    )


def _get_postgres_config(database_url):
    """Конфиг для Railway PostgreSQL."""
    return dj_database_url.parse(
        database_url,
        conn_max_age=600,
        ssl_require=os.environ.get('DB_SSL_REQUIRE', 'true').lower() in ('true', '1', 'yes'),
    )


def build_database_config():
    postgres_url = _get_postgres_url()

    # USE_LOCAL_DB=true → всегда SQLite (для оффлайн-разработки)
    use_local = os.environ.get('USE_LOCAL_DB', 'false').lower() in ('true', '1', 'yes')

    if use_local:
        databases = {'default': _get_sqlite_config()}
        # Если есть PostgreSQL URL — добавляем как второй алиас для синхронизации
        if postgres_url:
            databases['remote'] = _get_postgres_config(postgres_url)
        return databases

    # По умолчанию — PostgreSQL (Railway), если URL есть
    if postgres_url:
        databases = {'default': _get_postgres_config(postgres_url)}
        # SQLite доступна как 'local' алиас для синхронизации
        databases['local'] = _get_sqlite_config()
        return databases

    # Fallback: только SQLite
    return {'default': _get_sqlite_config()}


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-1ai(#r*ur=bli!qqv+bbv@!y&13)efy49u-$oc%^zcbu0h$@^0')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() in ('true', '1', 'yes')

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')

# Railway даёт переменную CSRF_TRUSTED_ORIGINS — нужна для POST-запросов
CSRF_TRUSTED_ORIGINS = os.environ.get('CSRF_TRUSTED_ORIGINS', 'http://127.0.0.1:8000,https://web-production-dae10.up.railway.app').split(',')

# Автоматически добавляем Railway домен (если есть)
RAILWAY_PUBLIC_DOMAIN = os.environ.get('RAILWAY_PUBLIC_DOMAIN', '')
if RAILWAY_PUBLIC_DOMAIN:
    railway_origin = f'https://{RAILWAY_PUBLIC_DOMAIN}'
    if railway_origin not in CSRF_TRUSTED_ORIGINS:
        CSRF_TRUSTED_ORIGINS.append(railway_origin)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'casino',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mmflip.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        # Добавляем путь к папке с шаблонами твоего приложения
        'DIRS': [BASE_DIR / 'casino' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mmflip.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database — Railway/PostgreSQL через DATABASE_PUBLIC_URL / DATABASE_URL / PG* переменные
# USE_LOCAL_DB=true → default=SQLite, remote=PostgreSQL
# USE_LOCAL_DB=false → default=PostgreSQL, local=SQLite
# Синхронизация: python manage.py syncdb --direction pull|push
DATABASES = build_database_config()

# Разрешаем миграции только на default БД
DATABASE_ROUTERS = []


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# Railway/Production: куда collectstatic собирает файлы
STATIC_ROOT = BASE_DIR / 'staticfiles'

# WhiteNoise — сжатие и кэширование статики
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Discord Webhook для логирования результатов игр
# Замени на свой URL вебхука из Discord (Server Settings -> Integrations -> Webhooks)
DISCORD_WEBHOOK_URL = os.environ.get('DISCORD_WEBHOOK_URL', '')
